### ISSUE TITLE
Toolchain.mk?

### ISSUE THREAD

**Issue by haylinmoore** [codehz/mcpe-mods-dev#2]
I have been trying to mess around a build a mod, but I keep getting 
Makefile:1: toolchain.mk: No such file or directory
make: *** No rule to make target 'toolchain.mk'.  Stop.

I notice is it in the .gitignore could you add it?

**Comment by codehz** [comment]
This repo is actually been deprecated and I just move to codehz/bedrockmod. https://github.com/codehz/bedrockmod

The new repo is friendly for third party mod, because I decided to using pure C++ (instead of mix c++ with nim)

If you really want to know the toolchain.mk, it is the content (just specify the path to Android NDK
```
NDK := /data/ndk
export CXX := $(NDK)/bin/i686-linux-android-g++
```
